//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AITInventoryManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartLocation
    {
        public int Id { get; set; }
        public string PartID { get; set; }
        public string LocationID { get; set; }
        public string Quantity { get; set; }
    }
}
